# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: notopia
service: notopia-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_PORT: ${env:DATABASE_PORT}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_NAME: ${env:DATABASE_NAME}
  region: eu-central-1

package:
  exclude:
    - images/**
    - .git/**
    - .env

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
      - http:
          method: ANY
          path: '{proxy+}'
    timeout: 50
