
name: CI/CD to DigitalOcean droplet

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Install dependencies
      # - name: Install dependencies
      #   run: npm install

      # Step 5: Copy the SSH key for EC2 access
      - name: Add SSH Key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          password: ${{ secrets.DO_PASSWORD }}
          port: 22
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.DO_PATH }}
            git pull origin main
            npm install
            pm2 restart all  # Assuming you're using PM2 to manage your Node.js app
